I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script
    idk "%(p_name) hey?"
TypeError: must be real number, not str

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script
    idk "%(p_name) hey?"
  File "/Applications/renpy-8.3.4-sdk/renpy/ast.py", line 2579, in execute
    Say.execute(self)
  File "/Applications/renpy-8.3.4-sdk/renpy/ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-8.3.4-sdk/renpy/exports/sayexports.py", line 121, in say
    what = what % tag_quoting_dict
TypeError: must be real number, not str

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Plave Otome 1.0
Tue Mar 25 15:48:42 2025
